services:
  nginx:
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    image: ${APP_NAME:-app}-prod/nginx
    restart: unless-stopped
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - 'app-storage:/var/www/html/storage'
    networks:
      - app-network
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: docker/prod/php/Dockerfile
    image: ${APP_NAME:-app}-prod/app
    restart: unless-stopped
    working_dir: /var/www/html
    env_file:
      - .env
    volumes:
      - 'app-storage:/var/www/html/storage'
    networks:
      - app-network
    depends_on:
      pgsql:
        condition: service_healthy
      redis:
        condition: service_healthy

  queue:
    image: ${APP_NAME:-app}-prod/app
    restart: unless-stopped
    working_dir: /var/www/html
    command: [ "php", "artisan", "queue:work", "redis", "--sleep=3", "--tries=3", "--max-time=3600" ]
    env_file:
      - .env
    volumes:
      - 'app-storage:/var/www/html/storage'
    networks:
      - app-network
    depends_on:
      - app
      - pgsql
      - redis

  scheduler:
    image: ${APP_NAME:-app}-prod/app
    restart: unless-stopped
    working_dir: /var/www/html
    command: [ "php", "artisan", "schedule:work" ]
    env_file:
      - .env
    volumes:
      - 'app-storage:/var/www/html/storage'
    networks:
      - app-network
    depends_on:
      - app
      - pgsql
      - redis

  pgsql:
    image: 'postgres:18-alpine'
    restart: unless-stopped
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'app-pgsql:/var/lib/postgresql/data'
      - './docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
    networks:
      - app-network
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${DB_DATABASE}'
        - '-U'
        - '${DB_USERNAME}'
      retries: 3
      timeout: 5s

  redis:
    image: 'redis:alpine'
    restart: unless-stopped
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'app-redis:/data'
    networks:
      - app-network
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

networks:
  app-network:
    driver: bridge

volumes:
  app-pgsql:
    driver: local
  app-redis:
    driver: local
  app-storage:
    driver: local
