services:
  nginx:
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    image: ${APP_NAME:-app}-prod/nginx
    restart: unless-stopped
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - 'app-storage:/var/www/html/storage'
    networks:
      - app-network
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: docker/prod/php/Dockerfile
    image: ${APP_NAME:-app}-prod/app
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      APP_NAME: '${APP_NAME:-Laravel}'
      APP_ENV: '${APP_ENV:-production}'
      APP_KEY: '${APP_KEY}'
      APP_DEBUG: '${APP_DEBUG:-false}'
      APP_URL: '${APP_URL}'
      APP_LOCALE: '${APP_LOCALE:-en}'
      APP_FALLBACK_LOCALE: '${APP_FALLBACK_LOCALE:-en}'
      APP_FAKER_LOCALE: '${APP_FAKER_LOCALE:-en_US}'
      APP_TIMEZONE: '${APP_TIMEZONE:-UTC}'
      LOG_CHANNEL: '${LOG_CHANNEL:-stack}'
      DB_CONNECTION: '${DB_CONNECTION:-pgsql}'
      DB_HOST: '${DB_HOST:-pgsql}'
      DB_PORT: '${DB_PORT:-5432}'
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
      BROADCAST_CONNECTION: '${BROADCAST_CONNECTION:-log}'
      CACHE_STORE: '${CACHE_STORE:-redis}'
      FILESYSTEM_DISK: '${FILESYSTEM_DISK:-local}'
      QUEUE_CONNECTION: '${QUEUE_CONNECTION:-redis}'
      SESSION_DRIVER: '${SESSION_DRIVER:-redis}'
      SESSION_LIFETIME: '${SESSION_LIFETIME:-120}'
      MEMCACHED_HOST: '${MEMCACHED_HOST:-127.0.0.1}'
      REDIS_CLIENT: '${REDIS_CLIENT:-phpredis}'
      REDIS_HOST: '${REDIS_HOST:-redis}'
      REDIS_PASSWORD: '${REDIS_PASSWORD:-null}'
      REDIS_PORT: '${REDIS_PORT:-6379}'
    volumes:
      - 'app-storage:/var/www/html/storage'
    networks:
      - app-network
    depends_on:
      pgsql:
        condition: service_healthy
      redis:
        condition: service_healthy

  queue:
    image: ${APP_NAME:-app}-prod/app
    restart: unless-stopped
    working_dir: /var/www/html
    command: [ "php", "artisan", "queue:work", "redis", "--sleep=3", "--tries=3", "--max-time=3600" ]
    environment:
      APP_NAME: '${APP_NAME:-Laravel}'
      APP_ENV: '${APP_ENV:-production}'
      APP_URL: '${APP_URL}'
      APP_KEY: '${APP_KEY}'
      APP_DEBUG: '${APP_DEBUG:-false}'
      APP_LOCALE: '${APP_LOCALE:-en}'
      APP_FALLBACK_LOCALE: '${APP_FALLBACK_LOCALE:-en}'
      APP_FAKER_LOCALE: '${APP_FAKER_LOCALE:-en_US}'
      APP_TIMEZONE: '${APP_TIMEZONE:-UTC}'
      DB_CONNECTION: '${DB_CONNECTION:-pgsql}'
      DB_HOST: '${DB_HOST:-pgsql}'
      DB_PORT: '${DB_PORT:-5432}'
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
      CACHE_STORE: '${CACHE_STORE:-redis}'
      QUEUE_CONNECTION: '${QUEUE_CONNECTION:-redis}'
      REDIS_CLIENT: '${REDIS_CLIENT:-phpredis}'
      REDIS_HOST: '${REDIS_HOST:-redis}'
      REDIS_PASSWORD: '${REDIS_PASSWORD:-null}'
      REDIS_PORT: '${REDIS_PORT:-6379}'
    volumes:
      - 'app-storage:/var/www/html/storage'
    networks:
      - app-network
    depends_on:
      - app
      - pgsql
      - redis

  scheduler:
    image: ${APP_NAME:-app}-prod/app
    restart: unless-stopped
    working_dir: /var/www/html
    command: [ "php", "artisan", "schedule:work" ]
    environment:
      APP_NAME: '${APP_NAME:-Laravel}'
      APP_ENV: '${APP_ENV:-production}'
      APP_URL: '${APP_URL}'
      APP_KEY: '${APP_KEY}'
      APP_DEBUG: '${APP_DEBUG:-false}'
      APP_LOCALE: '${APP_LOCALE:-en}'
      APP_FALLBACK_LOCALE: '${APP_FALLBACK_LOCALE:-en}'
      APP_FAKER_LOCALE: '${APP_FAKER_LOCALE:-en_US}'
      APP_TIMEZONE: '${APP_TIMEZONE:-UTC}'
      DB_CONNECTION: '${DB_CONNECTION:-pgsql}'
      DB_HOST: '${DB_HOST:-pgsql}'
      DB_PORT: '${DB_PORT:-5432}'
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
      CACHE_STORE: '${CACHE_STORE:-redis}'
      QUEUE_CONNECTION: '${QUEUE_CONNECTION:-redis}'
      REDIS_CLIENT: '${REDIS_CLIENT:-phpredis}'
      REDIS_HOST: '${REDIS_HOST:-redis}'
      REDIS_PASSWORD: '${REDIS_PASSWORD:-null}'
      REDIS_PORT: '${REDIS_PORT:-6379}'
    volumes:
      - 'app-storage:/var/www/html/storage'
    networks:
      - app-network
    depends_on:
      - app
      - pgsql
      - redis

  pgsql:
    image: 'postgres:18-alpine'
    restart: unless-stopped
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'app-pgsql:/var/lib/postgresql/data'
      - './docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
    networks:
      - app-network
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${DB_DATABASE}'
        - '-U'
        - '${DB_USERNAME}'
      retries: 3
      timeout: 5s

  redis:
    image: 'redis:alpine'
    restart: unless-stopped
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'app-redis:/data'
    networks:
      - app-network
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

networks:
  app-network:
    driver: bridge

volumes:
  app-pgsql:
    driver: local
  app-redis:
    driver: local
  app-storage:
    driver: local
